name = "kyle-j-mueller-com-static"
compatibility_date = "2026-05-07"

[assets]
directory = "."
not_found_handling = "single-page-application"

[[routes]]
pattern = "kylejmueller.com"
custom_domain = true

[[routes]]
pattern = "www.kylejmueller.com"
custom_domain = true
